- hosts: all
  gather_facts: no

  vars:
    new_user: newuser

  pre_tasks:
    - name: copy requirements.yml to server
      ansible.builtin.template:
        src: ../requirements.yml
        dest: /home/kate/requirements.yml
      become: yes  
    - name: execute ansible install roles
      ansible.builtin.shell: ansible-galaxy install -r requirements.yml

  roles:
    - name: geerlingguy.git
      vars:
        ansible_os_family: 'Debian'
      become: yes  
    - name: geerlingguy.nodejs
      vars:
        ansible_os_family: 'Debian'
        ansible_distribution_release: 'jammy'
      become: yes  
        
    - name: create-user 
      vars: 
        user: "{{ new_user }}"
      become: yes  

  post_tasks:

    - name: add SSH key
      ansible.posix.authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', '../files/id_rsa.pub') }}"
        path: "/home/{{ new_user }}/.ssh/authorized_keys" 
      become: yes   
      
