- hosts: servers 

  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html
    hostname_string: "This is server {{ ansible_hostname }}"
    current_date: "{{ ansible_date_time.epoch }}"

  tasks:

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes  
      tags: installation

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: latest
      become: yes  
      tags: installation  

    - name: Ensure a RU locale exists
      locale_gen:
        name: ru_RU.UTF-8
        state: present  
      notify:
        - restart nginx    
      # sudo dpkg-reconfigure locales    

    # - name: Set timezone to Europe/Moscow
    #   timezone:
    #     name: Europe/Moscow

    - name: set locale
      ansible.builtin.command: "date -d @{{ current_date }} '+%a, %d %B %Y %H:%M:%S'"
      register: local_date  
      # environment:
      #   LANG: ru_RU.UTF-8
      #   LC_ALL: ru_RU.UTF-8 

    # - name: set locale 
    #   ansible.builtin.command: date  "+%a, %d %B %Y %H:%M:%S"
    #   register: locale_date
    #   environment:
    #     LANG: ru_RU.UTF-8
    #     LC_ALL: ru_RU.UTF-8 
      
    - name: copy nginx.conf file
      ansible.builtin.template:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
        follow: yes
      notify:
        - restart nginx  
      become: yes  
      tags: files  

    - name: get cowsay template 
      ansible.builtin.shell: cowsay "This is server {{ ansible_hostname }}!"
      register: cowsay_result    

    - name: copy index.html file
      ansible.builtin.template:
        src: ../files/index.html.j2
        dest: "{{ root_dir }}/index.html"
        follow: yes
      become: yes  
      tags: files    

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes 