- hosts: servers 

  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html
    hostname_string: "This is server {{ ansible_hostname }}"
    current_date: "{{ ansible_date_time.epoch }}"

  tasks:

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: latest
      become: yes  
      tags: installation

    - name: get cowsay template 
      ansible.builtin.shell: cowsay "This is server {{ ansible_hostname }}!"
      register: cowsay_result  

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes  
      tags: installation

    - name: copy nginx.conf file
      ansible.builtin.template:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
        follow: yes
      notify:
        - restart nginx  
      become: yes  
      tags: files  

    - name: copy index.html file
      ansible.builtin.template:
        src: ../files/index.html.j2
        dest: "{{ root_dir }}/index.html"
        follow: yes
      become: yes  
      tags: files    

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes 